---
title: "Ruitian Liu"
---

I am a graduate student in the Department of Statistics at the University of California, Davis, where I began my M.S. in Statistics in 2025. 

## Academic interests 
Using statistical methods solving statistical signal processing (ML methods, image/audio signal, functional/longitudinal data analysis), model selection (sensitivity analysis, misspecified model, sampling), and applications in real world problem. In particular, my passion in music and film film drives me a lot to delve into some signal processing related problems.

I enjoy understanding the intuition behind the models that I have study, and I also like explaining these ideas to non-statisticians. I would like to further strengthen my theoretical foundation (especially in advanced analysis, optimization, measure theory, math stat and geometry) in order to gain a deeper and more rigorous understanding of these methods.

## Current Works (In Progress)
- Bias and causal inference in ML method for fake music detection
- Analysis and imputation of missing data under AR(1) setting
- Survey in sampling, MCMC

## Quick Links
- [Completed courses in undergraduates](undergraduate.qmd)
- [Completed or in progress courses in UCDavis](master.qmd)
- [Projects](projects.qmd)
- [CV](cv rttliu.pdf)

## Contact
- GitHub: https://github.com/rttliu
- Phone: +1-(628)-306-5325 or 
- Email: rttliu@ucdavis.edu / yktyxtt@outlook.com
