---
title: "Graduate Coursework"
page-layout: full
format:
  html:
    toc: false
---

### Fall 2025 (Overall GPA: 3.70)

- **STA 200A — Introduction to Probability** (Required, Master level) <br>
  Fundamental concepts of probability theory, discrete and continuous random variables, standard distributions, moments and moment-generating functions, laws of large numbers and the central limit theorem.

- **STA 206 — Statistical Research Method I** (Required, Master level) <br>
  Simple and multiple linear regression, polynomial regression, diagnostics, model selection, factorial designs and analysis of covariance. 

- **HDE 208 — Analysis of Intensive Longitudinal Data** (Ph.D level) <br>
  Manipulation, organization, description, and modeling of intensive longitudinal data (ILD), which are repeated measures collected intensively from individuals within a relatively short period of time. Daily diary data, ecological momentary assessments, neuroimaging data, and physiological recordings.

---

### Winter 2026

- **STA 145 — Bayesian Statistical Inference** (Undergraduate level) <br>
  Subjective probability, Bayes Theorem, conjugate priors, non-informative priors, estimation, testing, prediction, empirical Bayes methods, properties of Bayesian procedures, comparisons with classical procedures, approximation techniques, Gibbs sampling, hierarchical Bayesian analysis, applications, computer implemented data analysis.

- **STA 200B — Introduction to Mathematical Statistics I**  (Required, Master level) <br>
  Sampling, methods of estimation, bias-variance decomposition, sampling distributions, Fisher information, confidence intervals, and some elements of hypothesis testing.

- **STA 207 — Statistical Research Method II**  (Required, Master level) <br>
  Linear mixed models, repeated measures, generalized linear models, model selection, analysis of missing data, and multiple testing procedures.

- **STA 250 — Topics in Analysis of Object Data**  (Ph.D level) <br>
  Objects in Euclidean/Hilbert space, functional data analysis, basic tools for metric statistics, Wasserstein space, geodesic metric spaces.

---

### Spring 2026

- **STA 200C — Introduction to Mathematical Statistics II**  (Required, Master level) <br>
  Testing theory, tools and applications from probability theory, Linear model theory, ANOVA, goodness-of-fit.

- **STA 208 — Statistical Methods in Machine Learning** (Required, Master level) <br>
  Resampling methods, regularization techniques in regression and modern classification, cluster analysis and dimension reduction techniques.

- **STA 243 — Computational Statistics** (Ph.D level) <br>
  Numerical analysis; random number generation; computer experiments and resampling techniques (bootstrap, cross validation); numerical optimization; matrix decompositions and linear algebra computations; algorithms (markov chain monte carlo, expectation-maximization); algorithm design and efficiency; parallel and distributed computing.

- **ECS 271 — Machine Learning & Discovery** (Ph.D level) <br>
  Artificial intelligence techniques for knowledge acquisition by computers. Fundamental problems in machine learning and discovery. Systems that learn from examples, analogies, and solved problems. Systems that discover numerical laws and qualitative relationships. Projects centering on implementation and evaluation.
---

### Fall 2026 (Planned)

- **STA 231A — Mathematical Statistics I**  (Ph.D level) <br>
  Basics of Probability Theory, Multivariate normal Basics of Decision Theory (decision space, decision rule, loss, risk) Exponential families; MLE; Sufficiency, Cramer-Rao Inequality Asymptotics with application to MLEs (and generalization to M-estimation) 

- **STA 235A — Probability I**  (Ph.D level) <br>
  Probability measures, random variables, expected values, independence; strong and weak laws of large numbers; weak convergence and central limit theorem

- **MAT 258A — Numerical Optimization**  (Ph.D level) <br>
  Numerical methods for infinite dimensional optimization problems. Newton and Quasi-Newton methods, linear and sequential quadratic programming, barrier methods; large-scale optimization; theory of approximations; infinite and semi-infinite programming; applications to optimal control, stochastic optimization and distributed systems.

- **EEC 260 — Random Signals & Noise**  (Ph.D level) <br>
  Random processes as probabilistic models for signals and noise. Probability and random variables, Convergence and limit theorems, Specification of random processes, Markov Chains, Wiener process and white Gaussian noise, Poisson process and shot noise, Processing and frequency analysis of random signals.
---

### Winter 2027 (Planned)

- **STA 231B — Mathematical Statistics II**  (Ph.D level) <br>
  Testing/ Confidence Intervals (including FDR) Quadratic Forms (+ their distribution under normal) Confidence regions. Linear model (basic theory) LS-estimation, ANOVA, F-test Linear mixed model.

- **STA 260 — Statistical Practice and Data Analysis**  (Ph.D level) <br>
   Principles and practice of interdisciplinary collaboration in statistics, statistical consulting, ethical aspects, and basics of data analysis and study design. Emphasis on practical consulting and collaboration of statisticians with clients and scientists under instructor supervision.


---

### Spring 2027 (Planned)

- **STA 135 — Multivariate Data Analysis** (Required, Undergraduate level) <br>
  Multivariate normal distribution; Mahalanobis distance; sampling distributions of the mean vector and covariance matrix; Hotellings T2; simultaneous inference; one-way MANOVA; discriminant analysis; principal components; canonical correlation; factor analysis.

- **STA 231C — Mathematical Statistics III**  (Ph.D level) <br>
  Smoothing (kernel, local polynomial, splines), Statistical functionals (including basic bootstrap and jackknife), Optimization techniques (incl. EM-algorithm)

---
